### ISSUE TITLE
Practica de modelo de negocios

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/practica-de-modelo-de-negocios-disttecpersis#3]
[modelo de negocios.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-modelo-de-negocios-disttecpersis/files/7412195/modelo.de.negocios.pdf)

**Comment by KarlaV0** [comment]
19%

**Comment by josealfredo79** [comment]
Las conclusiones estan incompletas
